fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "bmmarwan64@gmail.com"
    sender_name: "Test"
  service:
    mailer: fos_user.mailer.twig_swift
  registration:
    confirmation:
      enabled: true
      from_email:
        address: bmmarwane64@gmail.com
        sender_name: Admin
      template: emails/email.html.twig

