vich_uploader:
    db_driver: orm

    mappings:
        photos:
            uri_prefix: /images/photo
            upload_destination: '%kernel.project_dir%/public/images/photos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: False
            delete_on_update: true
            delete_on_remove: true
